spring:
  application:
    name: "category"
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092

build:
  version: "1.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

service:
  max-parent-count: "4"
  contactInfo:
    message: "Welcome to category microservice related local APIs"
    contactDetails:
      name: "Tran Khanh Duy - Developer"
      email: "trankhanhduy18@gmail.com"
    onCallSupport:
      - 0xxxxxxxxx