spring:
  application:
    name: "class"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

build:
  version: "1.0"

service:
  contactInfo:
    message: "Welcome to class microservice related local APIs"
    contactDetails:
      name: "Tran Khanh Duy - Developer"
      email: "trankhanhduy18@gmail.com"
    onCallSupport:
      - 0xxxxxxxxx