spring:
  application:
    name: "notification"
  config:
    import:
      - "queue-common.yml"

build:
  version: "1.0"

user:
  message: "Welcome to notification microservice related production APIs"
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx