spring:
  application:
    name: "notification"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

build:
  version: "1.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

queue-list:
  exchange: default.exchange
  user-registered:
    queue: user.registered
    routing-key: user.registered.key
  user-verified:
    queue: user.verified
    routing-key: user.verified.key
  verification-mail-sent:
    queue: verification.mail.sent
    routing-key: verification.mail.sent.key

user:
  message: "Welcome to notification microservice related local APIs"
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx