spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue-list:
  exchange: default.exchange
  user-registered:
    queue: user.registered
    routing-key: user.registered.routingkey
  user-verified:
    queue: user.verified
    routing-key: user.verified.routingkey
  verification-mail-sent:
    queue: verification.mail.sent
    routing-key: verification.mail.sent.routingkey
