spring:
  application:
    name: "user"
  config:
    import:
      - "queue-common.yml"

build:
  version: "1.0"

verification:
  expired-time: 300

management:
  endpoints:
    web:
      exposure:
        include: *

user:
  message: "Welcome to user microservice related local APIs"
  contactDetails:
    name: "Tran Khanh Duy - Developer"
    email: "trankhanhduy18@gmail.com"
  onCallSupport:
    - 0xxxxxxxxx